theme = "solarized-dark"
icons = "awesome"

#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "nvidia_gpu"
#label = "GTX"
#show_memory = false
#show_clocks = true
#interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "pacman"
interval = 600

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min}° min, {max}° max, {average}° avg"

#[[block]]
#block = "sound"
#step_width = 3

[[block]]
block = "battery"
#interval = 10
#show = "both"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

