#spaceship_rename_terminal_window() {
#  #alacritty @ set-window-title "${PWD/#$HOME/~}"
#}
#
#export SPACESHIP_PROMPT_ORDER=(
#  rename_terminal_window
#  time
#  user
#  dir
#  host
#  git_branch
#  git_status
#  kubecontext
#  azure
#  exec_time
#  line_sep
#  jobs
#  char
#)
#
#export SPACESHIP_CHAR_SYMBOL="❯ "
#export SPACESHIP_JOBS_SYMBOL="»"
#export SPACESHIP_TIME_SHOW=true
#export SPACESHIP_USER_PREFIX="as "
#export SPACESHIP_USER_SHOW="needed"
#export SPACESHIP_DIR_TRUNC_PREFIX=".../"
#export SPACESHIP_DIR_TRUNC_REPO=false

POWERLEVEL9K_MODE="awesome-fontconfig"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

POWERLEVEL9K_FOLDER_ICON=""
#POWERLEVEL9K_HOME_SUB_ICON="$(print_icon "HOME_ICON")"
#POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") "

POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
POWERLEVEL9K_NVM_BACKGROUND="238"
POWERLEVEL9K_NVM_FOREGROUND="green"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="015"

POWERLEVEL9K_TIME_BACKGROUND='255'
#POWERLEVEL9K_COMMAND_TIME_FOREGROUND='gray'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'

POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time time)
POWERLEVEL9K_SHOW_CHANGESET=true
